import 'work_order_contract.dart';

abstract final class WorkOrderMockData {
  static const items = [
    WorkOrder(
      id: 'wo-1',
      code: 'WO-8901',
      title: 'Hydraulic Seal Replacement',
      assetName: 'Main Stamping Press 02',
      location: 'Plant 1 - Sector B',
      priority: WorkOrderPriority.urgent,
      status: WorkOrderStatus.inProgress,
      assignedTo: 'Alex Rivers',
      dueDate: 'Today, 14:00',
      description: 'Replace worn high-pressure seal to stop oil seepage and restore nominal bar pressure.',
      checklist: [
        WorkOrderChecklist(id: 'c1', label: 'Depressurize hydraulic circuit', isDone: true),
        WorkOrderChecklist(id: 'c2', label: 'Lockout/Tagout main electrical feeder', isDone: true),
        WorkOrderChecklist(id: 'c3', label: 'Remove flange collar and extract old seal', isDone: true),
        WorkOrderChecklist(id: 'c4', label: 'Clean seat and fit elastomeric ring', isDone: false),
        WorkOrderChecklist(id: 'c5', label: 'Pressurize to 180 bar and check leak integrity', isDone: false),
      ],
    ),
    WorkOrder(
      id: 'wo-2',
      code: 'WO-8902',
      title: 'Conveyor Motor Calibration',
      assetName: 'Assembly Line 1 Conveyor',
      location: 'Plant 1 - Sector A',
      priority: WorkOrderPriority.high,
      status: WorkOrderStatus.pending,
      assignedTo: 'Sarah Chen',
      dueDate: 'Today, 17:30',
      description: 'Variable frequency drive showing minor slip at 1200 RPM. Recalibrate PID parameters.',
      checklist: [
        WorkOrderChecklist(id: 'c1', label: 'Inspect belt tension and pulley alignment', isDone: false),
        WorkOrderChecklist(id: 'c2', label: 'Connect diagnostic handheld to drive', isDone: false),
        WorkOrderChecklist(id: 'c3', label: 'Execute auto-tuning cycle', isDone: false),
        WorkOrderChecklist(id: 'c4', label: 'Verify tachometer reading at nominal speed', isDone: false),
      ],
    ),
    WorkOrder(
      id: 'wo-3',
      code: 'WO-8903',
      title: 'Chiller Filter Inspection',
      assetName: 'HVAC Chiller Unit 4',
      location: 'Utility Building - Roof Level',
      priority: WorkOrderPriority.medium,
      status: WorkOrderStatus.pending,
      assignedTo: 'Marcus Brody',
      dueDate: 'Tomorrow, 09:00',
      description: 'Differential pressure sensor triggered advisory warning for primary particulate filter.',
      checklist: [
        WorkOrderChecklist(id: 'c1', label: 'Check differential pressure manometer', isDone: false),
        WorkOrderChecklist(id: 'c2', label: 'Remove intake pre-filter panel', isDone: false),
        WorkOrderChecklist(id: 'c3', label: 'Replace media cartridge if saturated', isDone: false),
      ],
    ),
    WorkOrder(
      id: 'wo-4',
      code: 'WO-8904',
      title: 'Packaging Arm Lubrication',
      assetName: 'Robotic Palletizer R-04',
      location: 'Packaging Hub - Bay 3',
      priority: WorkOrderPriority.low,
      status: WorkOrderStatus.completed,
      assignedTo: 'Alex Rivers',
      dueDate: 'Yesterday',
      description: 'Scheduled monthly lubrication of 6-axis articulation points with synthetic grease.',
      checklist: [
        WorkOrderChecklist(id: 'c1', label: 'Purge old grease from joint nipples', isDone: true),
        WorkOrderChecklist(id: 'c2', label: 'Inject food-grade lubricant', isDone: true),
        WorkOrderChecklist(id: 'c3', label: 'Run dry cycle and clean excess overflow', isDone: true),
      ],
    ),
    WorkOrder(
      id: 'wo-5',
      code: 'WO-8905',
      title: 'Coolant Flow Sensor Check',
      assetName: 'CNC Milling Center 08',
      location: 'Precision Machining Bay',
      priority: WorkOrderPriority.high,
      status: WorkOrderStatus.inProgress,
      assignedTo: 'David Kim',
      dueDate: 'Today, 16:00',
      description: 'Intermittent flow telemetry drops reported by machine operator during heavy cut cycles.',
      checklist: [
        WorkOrderChecklist(id: 'c1', label: 'Inspect flow switch wiring harness', isDone: true),
        WorkOrderChecklist(id: 'c2', label: 'Flush sensor orifice with air nozzle', isDone: false),
        WorkOrderChecklist(id: 'c3', label: 'Simulate flow and verify relay trip', isDone: false),
      ],
    ),
  ];
}
