import 'inventory_contract.dart';

abstract final class InventoryMockData {
  static const items = [
    InventoryItem(
      id: 'inv-1',
      code: 'SKU-1024',
      name: 'Industrial Bearing SKF 6204',
      category: 'Mechanical Parts',
      quantity: 184,
      minThreshold: 50,
      unit: 'pcs',
      binLocation: 'Aisle 2 - Bin A04',
      status: StockStatus.inStock,
      lastRestocked: '3 days ago',
    ),
    InventoryItem(
      id: 'inv-2',
      code: 'SKU-2051',
      name: 'Hydraulic Oil ISO VG 46',
      category: 'Lubricants & Fluids',
      quantity: 6,
      minThreshold: 10,
      unit: 'drums',
      binLocation: 'Zone C - Bay 02',
      status: StockStatus.lowStock,
      lastRestocked: '1 week ago',
    ),
    InventoryItem(
      id: 'inv-3',
      code: 'SKU-3112',
      name: 'Nitrile O-Ring Seal Set',
      category: 'Seals & Gaskets',
      quantity: 42,
      minThreshold: 20,
      unit: 'sets',
      binLocation: 'Cabinet D - Shelf 3',
      status: StockStatus.inStock,
      lastRestocked: 'Yesterday',
    ),
    InventoryItem(
      id: 'inv-4',
      code: 'SKU-4401',
      name: 'Servo Drive Rotary Encoder',
      category: 'Electronics & Sensors',
      quantity: 2,
      minThreshold: 4,
      unit: 'units',
      binLocation: 'Clean Vault 01',
      status: StockStatus.lowStock,
      lastRestocked: '2 weeks ago',
    ),
    InventoryItem(
      id: 'inv-5',
      code: 'SKU-5209',
      name: 'Optical Proximity Sensor M12',
      category: 'Electronics & Sensors',
      quantity: 65,
      minThreshold: 25,
      unit: 'pcs',
      binLocation: 'Drawer E - Bin 12',
      status: StockStatus.inStock,
      lastRestocked: '4 days ago',
    ),
    InventoryItem(
      id: 'inv-6',
      code: 'SKU-6188',
      name: 'Carbon Steel Flange Gasket',
      category: 'Seals & Gaskets',
      quantity: 0,
      minThreshold: 15,
      unit: 'pcs',
      binLocation: 'Rack 1 - Bin F02',
      status: StockStatus.outOfStock,
      lastRestocked: '1 month ago',
    ),
  ];
}
